language: emacs-lisp
dist: trusty

install:
  - curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/travis-eldev-and-evm > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use

env:
  # Not supported by Eldev; not terribly important.
  # - EVM_EMACS=emacs-24.1-travis
  # - EVM_EMACS=emacs-24.2-travis
  # - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-26.2-travis
  - EVM_EMACS=emacs-26.3-travis

script:
  - eldev -p -dtT test --expect 5
  - eldev -dtT compile --warnings-as-errors
